### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by FabriDamazio** [jhewlett/ValueObject#5]
Is this project no longer maintained?
I will use this Value Object implementation (using #2 #4 #1 ) in my [saas toolkit](https://github.com/FabriDamazio/amplifier).

**Comment by jhewlett** [comment]
I haven't given this much attention since initially releasing it. (Honestly, I wasn't really expecting anyone to use it!) I went ahead and merged the PR to upgrade to .NET Standard.

Is there something specific in the other PRs that you want? #2 seems like style changes only. #1 seems like it's trying to improve performance? I didn't quite understand that one.

Would you be interested in helping to maintain this?

**Comment by FabriDamazio** [comment]
@jhewlett tks for the response. 
#2 is just code style changes, but in my opinion, improve the code readability.
#1 we need more info about it. I didn't understand as well.

I liked your value object implementation and I'm using in my personal project Amplifier.

And sure, I can help to maintain this repo for sure.

**Comment by syedsuhaib** [comment]
Would be a great idea if the project were released as a NuGet package, so the wider community could benefit from using it. Right now, I am assuming, the only way to use it in my project is to just copy the [ValueObject.cs](https://github.com/jhewlett/ValueObject/blob/master/ValueObject/ValueObject.cs) file into my project?

**Comment by jhewlett** [comment]
@syedsuhaib It's on [nuget](https://www.nuget.org/packages/ValueObject/), I just hadn't release the netstandard version yet. Thanks for the reminder. I published the latest code as `0.6.1`

**Comment by syedsuhaib** [comment]
Thanks. There's no mention of the nuget package though in the [readme](https://github.com/jhewlett/ValueObject/blob/master/README.md). That's probably the first place folks are gonna look.

**Comment by syedsuhaib** [comment]
> 
> 
> @jhewlett tks for the response.
> #2 is just code style changes, but in my opinion, improve the code readability.
> #1 we need more info about it. I didn't understand as well.
> 
> I liked your value object implementation and I'm using in my personal project Amplifier.
> 
> And sure, I can help to maintain this repo for sure.

I have also refactored the code in my local version making it more readable using expression body for all overloads except the [GetHashCode()](https://github.com/jhewlett/ValueObject/blob/ff275822c0225e192ea12b247549d46c2826b517/ValueObject/ValueObject.cs#L78) function. If you're interested @jhewlett, I could send you a pull request?
